"""
ThreatIndicator — canonical data model for ActivGuard.

Every threat intelligence source (NVD, OSV, MISP, TAXII) normalises its output
into a ThreatIndicator before it is routed to the three detection layers.
This single-schema approach is a deliberate design choice: it decouples the
connector layer from the detection layer and enables heterogeneous feeds to
update Layers 1–3 uniformly via the ACP protocol.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Optional


@dataclass
class ThreatIndicator:
    """
    Canonical representation of a threat intelligence indicator.

    A ThreatIndicator encodes all information needed to update the three
    detection layers simultaneously:
      - Layer 1 (Activation Probe): ``activation_signature``
      - Layer 2 (Semantic RAG):     ``semantic_rule``
      - Layer 3 (Formal Verifier):  ``formal_property``

    The ``stix_pattern`` field stores the raw STIX 2.1 pattern string when the
    indicator was sourced from a STIX-speaking feed (TAXII, MISP), allowing
    exact round-trip serialisation back to STIX for downstream consumers.

    Attributes:
        id: Unique identifier — CVE ID (e.g. "CVE-2024-12345"), OSV ID
            (e.g. "GHSA-xxxx-xxxx-xxxx"), STIX indicator ID, or internal ID.
        source: Origin feed — "NVD", "OSV", "MISP", "TAXII", or "internal".
        severity: Qualitative severity class — "critical", "high", "medium",
            or "low".
        cwe: List of CWE identifiers (e.g. ["CWE-89", "CWE-639"]).
        affected_patterns: Code-level patterns that should be flagged (free
            text, fed to Layer 2 RAG as query terms).
        stix_pattern: Raw STIX 2.1 pattern string, if applicable.
        activation_signature: Serialised activation-space centroid used by
            Layer 1 to extend the probe without retraining.  Keys include
            "layer", "mean_activation", "variance", "vuln_class".
        semantic_rule: Natural-language security rule for Layer 2 RAG
            retrieval (e.g. "HTTP request with user-supplied URL — SSRF risk").
        formal_property: Nagini/Viper precondition string auto-generated by
            the STIXToViperGenerator for Layer 3, if available.
        timestamp: UTC time when the indicator was ingested.
        ttl: Time-to-live in seconds.  After expiry the indicator should be
            evicted from the live ChromaDB collection.
        description: Human-readable description of the vulnerability.
        cvss_score: CVSS v3.x base score (0.0–10.0).
        affected_packages: List of package identifiers
            (e.g. ["requests==2.25.0", "flask<2.3.0"]).
    """

    id: str
    source: str
    severity: str
    cwe: list[str]
    affected_patterns: list[str]
    stix_pattern: Optional[str]
    activation_signature: dict
    semantic_rule: str
    formal_property: Optional[str]
    timestamp: datetime
    ttl: int
    description: str = ""
    cvss_score: float = 0.0
    affected_packages: list[str] = field(default_factory=list)

    # ------------------------------------------------------------------
    # Validation helpers
    # ------------------------------------------------------------------

    def __post_init__(self) -> None:
        """Validate field values after construction."""
        valid_severities = {"critical", "high", "medium", "low", "unknown"}
        if self.severity not in valid_severities:
            raise ValueError(
                f"Invalid severity '{self.severity}'. "
                f"Must be one of {valid_severities}."
            )
        if not self.id:
            raise ValueError("ThreatIndicator.id must be a non-empty string.")
        if not isinstance(self.cvss_score, (int, float)):
            raise TypeError("cvss_score must be numeric.")
        if not (0.0 <= self.cvss_score <= 10.0):
            raise ValueError(
                f"cvss_score must be in [0.0, 10.0], got {self.cvss_score}."
            )
        if self.ttl < 0:
            raise ValueError(f"ttl must be non-negative, got {self.ttl}.")

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------

    def is_expired(self) -> bool:
        """Return True if the indicator has exceeded its TTL.

        Uses timezone-aware UTC comparison.  Indicators with ``ttl == 0``
        never expire and are treated as permanent entries (e.g. manually
        curated patterns).

        Returns:
            bool: True when the indicator should be evicted, False otherwise.
        """
        if self.ttl == 0:
            return False
        now = datetime.now(tz=timezone.utc)
        # Ensure timestamp is timezone-aware for comparison
        ts = self.timestamp
        if ts.tzinfo is None:
            ts = ts.replace(tzinfo=timezone.utc)
        age_seconds = (now - ts).total_seconds()
        return age_seconds > self.ttl

    # ------------------------------------------------------------------
    # Layer interface helpers
    # ------------------------------------------------------------------

    def to_semantic_pattern(self) -> str:
        """Compose a rich natural-language string for Layer 2 RAG indexing.

        The returned string combines the semantic rule, CWE identifiers, and
        affected code patterns into a single document that ChromaDB embeds.
        This maximises retrieval recall by ensuring multiple query vectors
        can surface the indicator.

        Returns:
            str: Formatted semantic document string.
        """
        cwe_str = ", ".join(self.cwe) if self.cwe else "CWE-unknown"
        patterns_str = "; ".join(self.affected_patterns) if self.affected_patterns else "N/A"
        return (
            f"[{self.id}] {self.semantic_rule} "
            f"| Severity: {self.severity} "
            f"| CWE: {cwe_str} "
            f"| Patterns: {patterns_str} "
            f"| Source: {self.source} "
            f"| Description: {self.description}"
        )

    # ------------------------------------------------------------------
    # Class methods
    # ------------------------------------------------------------------

    @classmethod
    def severity_from_cvss(cls, cvss: float) -> str:
        """Map a CVSS v3.x base score to a qualitative severity label.

        Thresholds follow the NVD severity classification:
        - Critical: 9.0 – 10.0
        - High:     7.0 – 8.9
        - Medium:   4.0 – 6.9
        - Low:      0.1 – 3.9
        - None:     0.0

        Args:
            cvss: CVSS base score in the range [0.0, 10.0].

        Returns:
            str: One of "critical", "high", "medium", "low", or "unknown".

        Raises:
            ValueError: If ``cvss`` is outside [0.0, 10.0].
        """
        if not (0.0 <= cvss <= 10.0):
            raise ValueError(f"CVSS score must be in [0.0, 10.0], got {cvss}.")
        if cvss >= 9.0:
            return "critical"
        if cvss >= 7.0:
            return "high"
        if cvss >= 4.0:
            return "medium"
        if cvss > 0.0:
            return "low"
        return "unknown"

    # ------------------------------------------------------------------
    # Serialisation
    # ------------------------------------------------------------------

    def to_dict(self) -> dict:
        """Serialise to a plain dictionary for JSON/JSONL export.

        Returns:
            dict: All fields serialised; ``datetime`` fields are ISO 8601
                strings.
        """
        return {
            "id": self.id,
            "source": self.source,
            "severity": self.severity,
            "cwe": self.cwe,
            "affected_patterns": self.affected_patterns,
            "stix_pattern": self.stix_pattern,
            "activation_signature": self.activation_signature,
            "semantic_rule": self.semantic_rule,
            "formal_property": self.formal_property,
            "timestamp": self.timestamp.isoformat(),
            "ttl": self.ttl,
            "description": self.description,
            "cvss_score": self.cvss_score,
            "affected_packages": self.affected_packages,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "ThreatIndicator":
        """Deserialise from a plain dictionary.

        Args:
            data: Dictionary matching the ThreatIndicator field schema.

        Returns:
            ThreatIndicator: Reconstructed indicator instance.
        """
        ts_raw = data.get("timestamp", datetime.now(tz=timezone.utc).isoformat())
        if isinstance(ts_raw, str):
            timestamp = datetime.fromisoformat(ts_raw)
        else:
            timestamp = ts_raw
        return cls(
            id=data["id"],
            source=data["source"],
            severity=data["severity"],
            cwe=data.get("cwe", []),
            affected_patterns=data.get("affected_patterns", []),
            stix_pattern=data.get("stix_pattern"),
            activation_signature=data.get("activation_signature", {}),
            semantic_rule=data.get("semantic_rule", ""),
            formal_property=data.get("formal_property"),
            timestamp=timestamp,
            ttl=data.get("ttl", 86400),
            description=data.get("description", ""),
            cvss_score=float(data.get("cvss_score", 0.0)),
            affected_packages=data.get("affected_packages", []),
        )

    def __repr__(self) -> str:
        return (
            f"ThreatIndicator(id={self.id!r}, source={self.source!r}, "
            f"severity={self.severity!r}, cvss={self.cvss_score})"
        )
