"""
HF Hidden-State Probe Training Script.

Loads all redbench samples (hand-written + generated + real/SecurityEval),
encodes them through the generating model's own residual stream, trains a
LogisticRegression probe, and saves the weights to disk.

Also runs a layer sweep (RQ1: which layer carries strongest vulnerability signal?)
and exports per-layer AUC results for the benchmark comparison.

Usage:
    cd activguard/
    python scripts/train_hf_probe.py
    python scripts/train_hf_probe.py --model Qwen/Qwen2.5-Coder-7B-Instruct
    python scripts/train_hf_probe.py --layer-sweep   # find best layer first
    python scripts/train_hf_probe.py --layer 14      # train on specific layer

Outputs:
    .activguard/hf_probe_{model_slug}.pkl    — trained probe weights
    .activguard/layer_sweep_{model_slug}.json — per-layer AUC table (if --layer-sweep)
    experiments.json                          — appended experiment record

Research context:
    Addresses RQ1 (layer sensitivity) and RQ4 (precision/recall tradeoff).
    The trained probe is wired into the proxy as the true L1 layer.
    Effective-rank diagnostics follow arXiv:2604.27019 to test whether
    vulnerability signatures occupy a low-dimensional residual-stream subspace.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import logging
import sys
import time
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).parent.parent))

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)s  %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger(__name__)

REDBENCH_DIR     = "../redbench/datasets"
EXPERIMENTS_FILE = "experiments.json"


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

def load_redbench_samples(redbench_dir: str) -> tuple[list[str], list[str], list[str]]:
    """Load all redbench samples and return (vuln_codes, safe_codes, class_labels).

    Loads from: samples.jsonl, samples_generated.jsonl,
                samples_generated_v2.jsonl, samples_real.jsonl

    Args:
        redbench_dir: Path to redbench/datasets/ directory.

    Returns:
        Tuple of (vuln_codes, safe_codes, class_labels).
    """
    base = Path(redbench_dir)
    vuln: list[str] = []
    safe: list[str] = []
    labels: list[str] = []

    source_files = [
        "samples.jsonl",
        "samples_generated.jsonl",
        "samples_generated_v2.jsonl",
        "samples_generated_v3.jsonl",
        "samples_real.jsonl",
        "samples_fixed.jsonl",   # safe fixes generated by fix_vuln_samples.py
    ]

    skipped_no_fix = 0

    for class_dir in sorted(d for d in base.iterdir() if d.is_dir()):
        vc = class_dir.name
        for fname in source_files:
            fp = class_dir / fname
            if not fp.exists():
                continue
            with open(fp, encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        s = json.loads(line)
                    except json.JSONDecodeError:
                        continue

                    code = s.get("code", "").strip()
                    fix  = s.get("fix", "").strip()

                    if not code:
                        continue
                    # Skip samples where the fix is just a TODO stub
                    if not fix or fix.startswith("# TODO"):
                        skipped_no_fix += 1
                        continue

                    vuln.append(code)
                    safe.append(fix)
                    labels.append(vc)

    logger.info(
        "Loaded %d samples (%d skipped — no fix code) across %d classes",
        len(vuln), skipped_no_fix,
        len(set(labels)),
    )
    if labels:
        class_counts = {vc: labels.count(vc) for vc in sorted(set(labels))}
        for vc, n in class_counts.items():
            logger.info("  %-22s %d pairs", vc, n)

    return vuln, safe, labels


# ---------------------------------------------------------------------------
# Layer sweep helper
# ---------------------------------------------------------------------------

def run_layer_sweep(
    probe_cls: type,
    model_name: str,
    vuln_codes: list[str],
    safe_codes: list[str],
    n_splits: int = 5,
    max_samples_per_class: int = 200,
) -> dict[int, dict]:
    """Encode all samples at every transformer layer and compare AUC.

    Resource-efficient: uses a single forward pass per sample and caches
    all layer vectors in RAM, then trains one probe per layer.

    Args:
        probe_cls: HFHiddenProbe class.
        model_name: HuggingFace model name.
        vuln_codes: Vulnerable code list.
        safe_codes: Safe code list.
        n_splits: CV folds for evaluation.
        max_samples_per_class: Cap to avoid OOM on large datasets.

    Returns:
        Dict mapping layer_index → evaluation metrics.
    """
    # Cap to avoid excessive memory usage
    n = min(len(vuln_codes), max_samples_per_class)
    vuln_sub = vuln_codes[:n]
    safe_sub = safe_codes[:n]
    all_codes = vuln_sub + safe_sub
    y = np.array([1] * n + [0] * n)

    logger.info(
        "Layer sweep: %d samples × 2 × all layers (model=%s)",
        n, model_name,
    )

    probe = probe_cls(model_name=model_name, layer=-1)
    tok, mdl = probe._tokenizer_and_model()
    n_layers = mdl.config.num_hidden_layers + 1

    # Collect all-layer vectors for each sample in one forward pass
    import torch
    all_layer_vecs: dict[int, list[np.ndarray]] = {li: [] for li in range(n_layers)}

    for i, code in enumerate(all_codes):
        inputs = tok(
            code, return_tensors="pt", truncation=True,
            max_length=1024, padding=False,
        )
        with torch.no_grad():
            out = mdl(**inputs, output_hidden_states=True)
        for li in range(n_layers):
            h = out.hidden_states[li][0, -1, :].cpu().float().numpy()
            all_layer_vecs[li].append(h)
        if (i + 1) % 20 == 0:
            logger.info("  Encoded %d/%d", i + 1, len(all_codes))

    # Build feature matrices
    X_all = {li: np.stack(vecs) for li, vecs in all_layer_vecs.items()}

    # Run layer sweep
    results = probe.layer_sweep(X_all, y, n_splits=n_splits)
    return results


# ---------------------------------------------------------------------------
# Experiment logging
# ---------------------------------------------------------------------------

def log_experiment(record: dict) -> None:
    """Append an experiment record to experiments.json.

    Format aligns with the local research logging convention.
    """
    exp_path = Path(EXPERIMENTS_FILE)
    experiments: list[dict] = []
    if exp_path.exists():
        with open(exp_path, encoding="utf-8") as f:
            try:
                experiments = json.load(f)
            except json.JSONDecodeError:
                experiments = []
    experiments.append(record)
    with open(exp_path, "w", encoding="utf-8") as f:
        json.dump(experiments, f, indent=2, ensure_ascii=False)
    logger.info("Experiment logged to %s", exp_path)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Train HF residual stream probe on redbench data",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--model",
        default="Qwen/Qwen2.5-Coder-1.5B-Instruct",
        help="HuggingFace model name (default: Qwen2.5-Coder-1.5B-Instruct)",
    )
    parser.add_argument(
        "--layer", type=int, default=-1,
        help="Transformer layer index to probe (-1 = last, default: -1)",
    )
    parser.add_argument(
        "--layer-sweep", action="store_true",
        help="Run AUC sweep across all transformer layers to find optimal layer",
    )
    parser.add_argument(
        "--redbench-dir", default=REDBENCH_DIR,
        help="Path to redbench/datasets/ directory",
    )
    parser.add_argument(
        "--n-splits", type=int, default=5,
        help="Number of CV folds for evaluation (default: 5)",
    )
    parser.add_argument(
        "--threshold", type=float, default=0.55,
        help="P(vulnerable) decision threshold (default: 0.55)",
    )
    parser.add_argument(
        "--probe-type", default="lr", choices=["mlp", "lr"],
        help="Probe classifier: lr (sklearn LogisticRegression, default) or mlp (PyTorch AdamW)",
    )
    parser.add_argument(
        "--no-cache", action="store_true",
        help="Force re-encoding even if cached feature matrix exists",
    )
    args = parser.parse_args()

    try:
        from probe.hf_hidden_probe import HFHiddenProbe
    except ImportError as exc:
        logger.error("Failed to import HFHiddenProbe: %s", exc)
        sys.exit(1)

    # ------------------------------------------------------------------
    # Load data
    # ------------------------------------------------------------------
    vuln_codes, safe_codes, class_labels = load_redbench_samples(args.redbench_dir)
    if not vuln_codes:
        logger.error("No samples found in %s — check the path.", args.redbench_dir)
        sys.exit(1)

    n_total = len(vuln_codes)

    # ------------------------------------------------------------------
    # Optional layer sweep (RQ1)
    # ------------------------------------------------------------------
    best_layer = args.layer

    if args.layer_sweep:
        logger.info("\n=== Layer Sweep (RQ1) ===")
        sweep_results = run_layer_sweep(
            HFHiddenProbe,
            args.model,
            vuln_codes,
            safe_codes,
            n_splits=args.n_splits,
        )
        # Find best layer by AUC
        best_layer = max(sweep_results, key=lambda li: sweep_results[li]["mean_auc"])
        best_auc = sweep_results[best_layer]["mean_auc"]
        logger.info("\nLayer sweep results:")
        logger.info("  %-8s %-8s %-8s", "Layer", "AUC", "F1")
        for li in sorted(sweep_results):
            m = sweep_results[li]
            marker = " *" if li == best_layer else ""
            logger.info("  %-8d %-8.3f %-8.3f%s", li, m["mean_auc"], m["mean_f1"], marker)
        logger.info("\nBest layer: %d (AUC=%.3f)", best_layer, best_auc)

        # Save sweep results
        sweep_slug = args.model.lower().split("/")[-1].replace(".", "-")
        sweep_path = Path(f".activguard/layer_sweep_{sweep_slug}.json")
        sweep_path.parent.mkdir(parents=True, exist_ok=True)
        with open(sweep_path, "w") as f:
            json.dump(
                {str(k): v for k, v in sweep_results.items()},
                f, indent=2,
            )
        logger.info("Layer sweep saved → %s", sweep_path)

    # ------------------------------------------------------------------
    # Train final probe on chosen layer
    # ------------------------------------------------------------------
    logger.info("\n=== Training HF Hidden-State Probe ===")
    logger.info("Model: %s  Layer: %d  Samples: %d+%d", args.model, best_layer, n_total, n_total)

    probe = HFHiddenProbe(
        model_name=args.model,
        layer=best_layer,
        threshold=args.threshold,
        probe_type=args.probe_type,
    )

    # ------------------------------------------------------------------
    # Feature matrix with disk cache
    # ------------------------------------------------------------------
    cache_dir = Path(".activguard")
    cache_dir.mkdir(parents=True, exist_ok=True)

    # Cache key = hash of (model, layer, all code snippets)
    cache_hash = hashlib.sha256(
        f"{args.model}:{best_layer}:{len(vuln_codes)}"
        .encode()
        + "".join(vuln_codes[:10] + safe_codes[:10]).encode()
    ).hexdigest()[:16]
    cache_path = cache_dir / f"features_{cache_hash}.npz"

    if cache_path.exists() and not args.no_cache:
        logger.info("Loading cached feature matrix from %s", cache_path)
        cached = np.load(cache_path)
        X, y = cached["X"], cached["y"]
        encode_time = 0.0
        logger.info("Feature matrix: shape=%s  (cached)", X.shape)
    else:
        t0 = time.time()
        X, y = probe.build_feature_matrix(vuln_codes, safe_codes, verbose=True)
        encode_time = time.time() - t0
        logger.info("Feature matrix: shape=%s  encode_time=%.1fs", X.shape, encode_time)
        np.savez_compressed(cache_path, X=X, y=y)
        logger.info("Feature matrix cached → %s", cache_path)

    metrics = probe.fit_and_evaluate(X, y, n_splits=args.n_splits)
    logger.info("\nCross-validation results (%d folds):", args.n_splits)
    logger.info("  AUC:  %.3f ± %.3f", metrics["mean_auc"], metrics["std_auc"])
    logger.info("  F1:   %.3f ± %.3f", metrics["mean_f1"], metrics["std_f1"])
    logger.info("  Effective rank: %.3f", metrics["mean_effective_rank"])
    if metrics.get("cv_direction_effective_rank"):
        logger.info(
            "  CV direction effective rank: %.3f",
            metrics["cv_direction_effective_rank"],
        )
    logger.info("  Per-fold AUC: %s", metrics["per_fold_auc"])

    # Save probe
    save_path = probe.save()
    logger.info("\nProbe saved → %s", save_path)

    # ------------------------------------------------------------------
    # Log experiment
    # ------------------------------------------------------------------
    experiment = {
        "timestamp": time.strftime("%Y-%m-%dT%H:%M:%S"),
        "experiment": "hf_hidden_probe_training",
        "model": args.model,
        "layer": best_layer,
        "threshold": args.threshold,
        "probe_type": args.probe_type,
        "n_vuln": n_total,
        "n_safe": n_total,
        "n_classes": len(set(class_labels)),
        "cv_folds": args.n_splits,
        "mean_auc": metrics["mean_auc"],
        "std_auc": metrics["std_auc"],
        "mean_f1": metrics["mean_f1"],
        "std_f1": metrics["std_f1"],
        "per_fold_auc": metrics["per_fold_auc"],
        "mean_effective_rank": metrics["mean_effective_rank"],
        "per_fold_effective_rank": metrics["per_fold_effective_rank"],
        "cv_direction_effective_rank": metrics["cv_direction_effective_rank"],
        "cv_direction_stable_rank": metrics["cv_direction_stable_rank"],
        "encode_time_s": round(encode_time, 1),
        "weights_path": save_path,
    }
    log_experiment(experiment)

    print("\n" + "=" * 60)
    print(f"  HF Hidden-State Probe Training Complete")
    print(f"  Model:   {args.model}")
    print(f"  Layer:   {best_layer}")
    print(f"  AUC:     {metrics['mean_auc']:.3f} +/- {metrics['std_auc']:.3f}")
    print(f"  F1:      {metrics['mean_f1']:.3f} +/- {metrics['std_f1']:.3f}")
    print(f"  EffRank: {metrics['mean_effective_rank']:.3f}")
    print(f"  Samples: {n_total} vuln + {n_total} safe")
    print(f"  Weights: {save_path}")
    print("=" * 60)


if __name__ == "__main__":
    main()
